### ISSUE TITLE
Cards module

### ISSUE THREAD

**Issue by Treadstudio** [markendley/soda#3]
1. not all images are displaying

2. small glitch showing on the end of scroll (it skips)

3. let's slow it down 30%

![Screenshot 2023-07-03 14 31 10](https://github.com/markendley/soda/assets/90736622/d32559ce-1657-432a-aa69-98bfb0d8a325)

**Comment by markendley** [comment]
fixed

**Comment by Treadstudio** [comment]
still getting a little bug with the images 

![Screenshot 2023-07-03 20 51 14](https://github.com/markendley/soda/assets/90736622/bdf561c4-e40d-4e4a-8e9d-83c129ad881a)

**Comment by markendley** [comment]
https://demoplatform.net/soda/inventory-finance/

I'm still seeing them all?
